name: Test Cron Job
on:
  workflow_dispatch: # manually trigger
  schedule:
    - cron: '*/5 * * * *' # Every 5 mins

jobs:
  ping:
    runs-on: ubuntu-latest

    env:
      LIVE_API_URL: ${{ secrets.LIVE_API_URL }}
      CRON_API_KEY: ${{ secrets.CRON_API_KEY }}

    steps:
      - name: Make HTTP request with auth header

        # set -euo pipefail (prevent bad url from executing)
        # --max-time : 30-60 second cold start
        # --fail : will fail on non 2XX responses
        run: |
          set -euo pipefail
          
          echo "Calling: $LIVE_API_URL"
        
          curl -X GET "$LIVE_API_URL" \
            -H "Authorization: Bearer $CRON_API_KEY" \
            --max-time 90 \
            --fail
