name: PR Checks

on:
  pull_request:
    branches:
      - develop
      - main

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    env:
      APP_STAGE: prod
      CORS_ORIGINS: test
      API_URL: https://test
      NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.TEST_SUPABASE_URL }}
      NEXT_PUBLIC_SUPABASE_ANON_KEY: 12345678901
      PRIVATE_SUPABASE_NODE_SERVICE_KEY: 7891011121314151617
      SAPOL_LOCATIONS_REQUEST_OPTS: ${{ vars.TEST_SAPOL_LOCATIONS_REQUEST_OPTS }}
      SAPOL_MOCK_RESPONSE_FILE_PATHS: ${{ vars.TEST_SAPOL_MOCK_RESPONSE_FILE_PATHS }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test

  lint:
    name: Run Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run lint
        run: npm run lint